Se crea una expectativa de los métodos to_s, get_name, get_proteinas, get_glucidos y get_lipidos rspec -I. spec/alimento_spec.rb
Alimento
  # Existencia de las características del Alimento
    Se almacena correctamente el nombre del alimento
    Se almacena correctamente las proteínas del alimento
    Se almacena correctamente los glúcidos del alimento
    Se almacena correctamente los lípidos del alimento
  # Existencia de los métodos de la clase Alimento
    Se realiza correctamente el to_s
    Se obtiene correctamente el nombre del alimento mediante el método get_name (FAILED - 1)
    Se obtiene correctamente las proteinas del alimento mediante el método get_proteinas (FAILED - 2)
    Se obtiene correctamente los glúcidos del alimento mediante el método get_glucidos (FAILED - 3)
    Se obtiene correctamente los lípidos del alimento mediante el método get_lipidos (FAILED - 4)

Failures:

  1) Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente el nombre del alimento mediante el método get_name
     Failure/Error: expect(@food1.get_name).to eq("Huevo frito")

     NoMethodError:
       undefined method `get_name' for #<Alimento:0x00000002c35080>
     # ./spec/alimento_spec.rb:50:in `block (3 levels) in <top (required)>'

  2) Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente las proteinas del alimento mediante el método get_proteinas
     Failure/Error: expect(@food1.get_proteinas).to eq(14.1)

     NoMethodError:
       undefined method `get_proteinas' for #<Alimento:0x00000002c2d808>
     # ./spec/alimento_spec.rb:53:in `block (3 levels) in <top (required)>'

  3) Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente los glúcidos del alimento mediante el método get_glucidos
     Failure/Error: expect(@food1.get_glucidos).to eq(0.0)

     NoMethodError:
       undefined method `get_glucidos' for #<Alimento:0x00000002c16e00>
       Did you mean?  glucidos
     # ./spec/alimento_spec.rb:56:in `block (3 levels) in <top (required)>'

  4) Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente los lípidos del alimento mediante el método get_lipidos
     Failure/Error: expect(@food1.get_grasas).to eq(19.5)

     NoMethodError:
       undefined method `get_grasas' for #<Alimento:0x00000002c13ae8>
     # ./spec/alimento_spec.rb:59:in `block (3 levels) in <top (required)>'

Finished in 0.00261 seconds (files took 0.08957 seconds to load)
9 examples, 4 failures

Failed examples:

rspec ./spec/alimento_spec.rb:49 # Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente el nombre del alimento mediante el método get_name
rspec ./spec/alimento_spec.rb:52 # Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente las proteinas del alimento mediante el método get_proteinas
rspec ./spec/alimento_spec.rb:55 # Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente los glúcidos del alimento mediante el método get_glucidos
rspec ./spec/alimento_spec.rb:58 # Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente los lípidos del alimento mediante el método get_lipidos

rake aborted!
Command failed with status (1): [rspec -I. spec/alimento_spec.rb...]
/home/victoria/LPP17-18/prct06/Rakefile:8:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)