Creadas las expectativas de la clase Lista con los siguientes errores: rspec -I. spec/listadll_spec.rb
Listadll
  Nododll
    #Debe existir un Nodo de la lista doblemente enlazada y el siguiente. Nodo inicializado correctamente (FAILED - 1)
  Listadll
    #Se hace un push por delante (FAILED - 2)
    #Se hace un push por detras (FAILED - 3)
    #Se pueden insertar varios elementos por delante (FAILED - 4)
    #Se pueden insertar varios elementos por detras (FAILED - 5)
    #Debe existir una Lista con su cabecera (FAILED - 6)
    #Debe existir una Lista con su cola (FAILED - 7)
    #Se hace un pop por delante (FAILED - 8)

Failures:

  1) Listadll Nododll #Debe existir un Nodo de la lista doblemente enlazada y el siguiente. Nodo inicializado correctamente
     Failure/Error: expect(@nod.value).to eq(12)

     NoMethodError:
       undefined method `value' for #<struct Nodedll val=12, sig=nil, prev=nil>
       Did you mean?  values
                      values_at
                      val
                      val=
     # ./spec/listadll_spec.rb:13:in `block (3 levels) in <top (required)>'

  2) Listadll Listadll #Se hace un push por delante
     Failure/Error: expect(@lista.pushfront(12)).to eq(12)

     NoMethodError:
       undefined method `pushfront' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:21:in `block (3 levels) in <top (required)>'

  3) Listadll Listadll #Se hace un push por detras
     Failure/Error: expect(@lista.pushback(12)).to eq(12)

     NoMethodError:
       undefined method `pushback' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:24:in `block (3 levels) in <top (required)>'

  4) Listadll Listadll #Se pueden insertar varios elementos por delante
     Failure/Error: expect(@lista.pushfront([13,14,15])).to eq(15)

     NoMethodError:
       undefined method `pushfront' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:28:in `block (3 levels) in <top (required)>'

  5) Listadll Listadll #Se pueden insertar varios elementos por detras
     Failure/Error: expect(@lista.pushback([13,14,15])).to eq(15)

     NoMethodError:
       undefined method `pushback' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:31:in `block (3 levels) in <top (required)>'

  6) Listadll Listadll #Debe existir una Lista con su cabecera
     Failure/Error: expect(@lista.head.value).to eq(15)

     NoMethodError:
       undefined method `head' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:36:in `block (3 levels) in <top (required)>'

  7) Listadll Listadll #Debe existir una Lista con su cola
     Failure/Error: expect(@lista.tail.value).to eq(15)

     NoMethodError:
       undefined method `tail' for #<Listadll:0x0000000166b8d0>
       Did you mean?  taint
     # ./spec/listadll_spec.rb:39:in `block (3 levels) in <top (required)>'

  8) Listadll Listadll #Se hace un pop por delante
     Failure/Error: expect(@lista.popfront).to eq(15)

     NoMethodError:
       undefined method `popfront' for #<Listadll:0x0000000166b8d0>
     # ./spec/listadll_spec.rb:43:in `block (3 levels) in <top (required)>'

Finished in 0.00218 seconds (files took 0.08983 seconds to load)
8 examples, 8 failures

Failed examples:

rspec ./spec/listadll_spec.rb:12 # Listadll Nododll #Debe existir un Nodo de la lista doblemente enlazada y el siguiente. Nodo inicializado correctamente
rspec ./spec/listadll_spec.rb:20 # Listadll Listadll #Se hace un push por delante
rspec ./spec/listadll_spec.rb:23 # Listadll Listadll #Se hace un push por detras
rspec ./spec/listadll_spec.rb:27 # Listadll Listadll #Se pueden insertar varios elementos por delante
rspec ./spec/listadll_spec.rb:30 # Listadll Listadll #Se pueden insertar varios elementos por detras
rspec ./spec/listadll_spec.rb:35 # Listadll Listadll #Debe existir una Lista con su cabecera
rspec ./spec/listadll_spec.rb:38 # Listadll Listadll #Debe existir una Lista con su cola
rspec ./spec/listadll_spec.rb:42 # Listadll Listadll #Se hace un pop por delante

rake aborted!
Command failed with status (1): [rspec -I. spec/listadll_spec.rb...]
/home/victoria/LPP17-18/prct06/Rakefile:13:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)