Se crea una expectativa del método get_valor_energetico rspec -I. spec/alimento_spec.rb
Alimento
  # Existencia de las características del Alimento
    Se almacena correctamente el nombre del alimento
    Se almacena correctamente las proteínas del alimento
    Se almacena correctamente los glúcidos del alimento
    Se almacena correctamente los lípidos del alimento
  # Existencia de los métodos de la clase Alimento
    Se realiza correctamente el to_s
    Se obtiene correctamente el nombre del alimento mediante el método get_name
    Se obtiene correctamente las proteinas del alimento mediante el método get_proteinas
    Se obtiene correctamente los glúcidos del alimento mediante el método get_glucidos
    Se obtiene correctamente los lípidos del alimento mediante el método get_lipidos
    Se obtiene correctamente el valor calórico del alimento (FAILED - 1)

Failures:

  1) Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente el valor calórico del alimento
     Failure/Error: expect(@food1.get_valor_energetico).to eq(231.9)

     NoMethodError:
       undefined method `get_valor_energetico' for #<Alimento:0x00000001e8b0b0>
     # ./spec/alimento_spec.rb:62:in `block (3 levels) in <top (required)>'

Finished in 0.00303 seconds (files took 0.09175 seconds to load)
10 examples, 1 failure

Failed examples:

rspec ./spec/alimento_spec.rb:61 # Alimento# Existencia de los métodos de la clase Alimento Se obtiene correctamente el valor calórico del alimento

rake aborted!
Command failed with status (1): [rspec -I. spec/alimento_spec.rb...]
/home/victoria/LPP17-18/prct06/Rakefile:8:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)