Creada la expectativa del for rspec -I. spec/loop_spec.rb
Alimento
  For, each y sort
    #Se realiza correctamente el for (FAILED - 1)

Failures:

  1) Alimento For, each y sort #Se realiza correctamente el for
     Failure/Error: expect(aux).to eq([@food16,@food21, @food17, @food18, @food22, @food2, @food3, @food15, @food7, @food19, @food5, @food6, @food4, @food9, @food8, @food1, @food14, @food13, @food11, @food12, @food20, @food10])

     NameError:
       undefined local variable or method `aux' for #<RSpec::ExampleGroups::Alimento::ForEachYSort:0x000000024734f0>
     # ./spec/loop_spec.rb:32:in `block (3 levels) in <top (required)>'

Finished in 0.00098 seconds (files took 0.09447 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/loop_spec.rb:31 # Alimento For, each y sort #Se realiza correctamente el for

rake aborted!
Command failed with status (1): [rspec -I. spec/loop_spec.rb...]
/home/victoria/LPP17-18/practicaLPP/Rakefile:27:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)