Añadiendo expectativas de enumerable con lista de numeros. Con errores. Enumerable con lista de numeros     #Se hacer correctamente min (FAILED - 1)     #Se hacer correctamente sort (FAILED - 2)     #Se hacer correctamente max (FAILED - 3)     #Se hacer correctamente collect (FAILED - 4)     #Se hacer correctamente map (FAILED - 5)     #Se hacer correctamente find (FAILED - 6)
Failures:

  1) Alimento Enumerable con lista de numeros #Se hacer correctamente min
     Failure/Error: expect(@list.min).to eq(1)

     NoMethodError:
       undefined method `min' for #<Listadll:0x00000001f428f0>
     # ./spec/comp_y_enum_spec.rb:75:in `block (3 levels) in <top (required)>'

  2) Alimento Enumerable con lista de numeros #Se hacer correctamente sort
     Failure/Error: expect(@list.sort).to eq([1,12,18])

     NoMethodError:
       undefined method `sort' for #<Listadll:0x00000001f428f0>
     # ./spec/comp_y_enum_spec.rb:78:in `block (3 levels) in <top (required)>'

  3) Alimento Enumerable con lista de numeros #Se hacer correctamente max
     Failure/Error: expect(@list.max).to eq(18)

     NoMethodError:
       undefined method `max' for #<Listadll:0x00000001f428f0>
     # ./spec/comp_y_enum_spec.rb:81:in `block (3 levels) in <top (required)>'

  4) Alimento Enumerable con lista de numeros #Se hacer correctamente collect
     Failure/Error: expect(@list.collect{ |x| x*x }).to eq([1, 144, 324 ])

     NoMethodError:
       undefined method `collect' for #<Listadll:0x00000001f428f0>
     # ./spec/comp_y_enum_spec.rb:84:in `block (3 levels) in <top (required)>'

  5) Alimento Enumerable con lista de numeros #Se hacer correctamente map
     Failure/Error: expect(@list.map { |x| x*2  }).to eq([2, 24, 36])

     NoMethodError:
       undefined method `map' for #<Listadll:0x00000001f428f0>
       Did you mean?  tap
     # ./spec/comp_y_enum_spec.rb:87:in `block (3 levels) in <top (required)>'

  6) Alimento Enumerable con lista de numeros #Se hacer correctamente find
     Failure/Error: expect(@list.find{ |x| x==18 }).to eq(18)

     NoMethodError:
       undefined method `find' for #<Listadll:0x00000001f428f0>
     # ./spec/comp_y_enum_spec.rb:90:in `block (3 levels) in <top (required)>'

Finished in 0.00366 seconds (files took 0.09077 seconds to load)
11 examples, 6 failures

Failed examples:

rspec ./spec/comp_y_enum_spec.rb:74 # Alimento Enumerable con lista de numeros #Se hacer correctamente min
rspec ./spec/comp_y_enum_spec.rb:77 # Alimento Enumerable con lista de numeros #Se hacer correctamente sort
rspec ./spec/comp_y_enum_spec.rb:80 # Alimento Enumerable con lista de numeros #Se hacer correctamente max
rspec ./spec/comp_y_enum_spec.rb:83 # Alimento Enumerable con lista de numeros #Se hacer correctamente collect
rspec ./spec/comp_y_enum_spec.rb:86 # Alimento Enumerable con lista de numeros #Se hacer correctamente map
rspec ./spec/comp_y_enum_spec.rb:89 # Alimento Enumerable con lista de numeros #Se hacer correctamente find

rake aborted!
Command failed with status (1): [rspec -I. spec/comp_y_enum_spec.rb...]
/home/victoria/LPP17-18/prct06/Rakefile:18:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)