Creada la expectativa de comparable (con errores). rspec -I. spec/comp_y_enum_spec.rb
Alimento
  Comparable con Alimento
    #Se hacer correctamente el > (FAILED - 1)
    #Se hacer correctamente el >= (FAILED - 2)
    #Se hacer correctamente el < (FAILED - 3)
    #Se hacer correctamente el <= (FAILED - 4)
    #Se hacer correctamente el entre dos valores (FAILED - 5)

Failures:

  1) Alimento Comparable con Alimento #Se hacer correctamente el >
     Failure/Error: expect(@food1 > @food2).to eq(true)

     NoMethodError:
       undefined method `>' for #<Alimento:0x0000000216db48>
     # ./spec/comp_y_enum_spec.rb:51:in `block (3 levels) in <top (required)>'

  2) Alimento Comparable con Alimento #Se hacer correctamente el >=
     Failure/Error: expect(@food1 >= @food2).to eq(true)

     NoMethodError:
       undefined method `>=' for #<Alimento:0x0000000216db48>
     # ./spec/comp_y_enum_spec.rb:54:in `block (3 levels) in <top (required)>'

  3) Alimento Comparable con Alimento #Se hacer correctamente el <
     Failure/Error: expect(@food5 < @food4).to eq(false)

     NoMethodError:
       undefined method `<' for #<Alimento:0x0000000216da08>
     # ./spec/comp_y_enum_spec.rb:57:in `block (3 levels) in <top (required)>'

  4) Alimento Comparable con Alimento #Se hacer correctamente el <=
     Failure/Error: expect(@food5 <= @food3).to eq(true)

     NoMethodError:
       undefined method `<=' for #<Alimento:0x0000000216da08>
       Did you mean?  <=>
     # ./spec/comp_y_enum_spec.rb:60:in `block (3 levels) in <top (required)>'

  5) Alimento Comparable con Alimento #Se hacer correctamente el entre dos valores
     Failure/Error: expect(@food5.between?(@food2, @food3)).to eq(true)

     NoMethodError:
       undefined method `between?' for #<Alimento:0x0000000216da08>
     # ./spec/comp_y_enum_spec.rb:63:in `block (3 levels) in <top (required)>'

Finished in 0.00182 seconds (files took 0.08958 seconds to load)
5 examples, 5 failures

Failed examples:

rspec ./spec/comp_y_enum_spec.rb:50 # Alimento Comparable con Alimento #Se hacer correctamente el >
rspec ./spec/comp_y_enum_spec.rb:53 # Alimento Comparable con Alimento #Se hacer correctamente el >=
rspec ./spec/comp_y_enum_spec.rb:56 # Alimento Comparable con Alimento #Se hacer correctamente el <
rspec ./spec/comp_y_enum_spec.rb:59 # Alimento Comparable con Alimento #Se hacer correctamente el <=
rspec ./spec/comp_y_enum_spec.rb:62 # Alimento Comparable con Alimento #Se hacer correctamente el entre dos valores

rake aborted!
Command failed with status (1): [rspec -I. spec/comp_y_enum_spec.rb...]
/home/victoria/LPP17-18/prct06/Rakefile:18:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)