Creada expectativa del metodo aibc_glucosa rspec -I. spec/alimento2_spec.rb
Alimento2
  Existencia de los métodos de Alimento
    #Se realiza correctamente el aibc_alim
    #Se realiza correctamente el aibc_glucosa (FAILED - 1)

Failures:

  1) Alimento2 Existencia de los métodos de Alimento #Se realiza correctamente el aibc_glucosa
     Failure/Error: expect(@individuos[0][0].aibc_glucosa(@glucosa1)).to eq(251.5)

     NoMethodError:
       undefined method `aibc_glucosa' for #<Alimento2:0x0000000282b908>
     # ./spec/alimento2_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.00147 seconds (files took 0.10801 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/alimento2_spec.rb:20 # Alimento2 Existencia de los métodos de Alimento #Se realiza correctamente el aibc_glucosa

rake aborted!
Command failed with status (1): [rspec -I. spec/alimento2_spec.rb...]
/home/victoria/LPP17-18/practicaLPP/Rakefile:22:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)