Creada la expectativa de each rspec -I. spec/loop_spec.rb
Alimento
  For, each y sort
    #Se realiza correctamente el for
    #Se realiza correctamente el each (FAILED - 1)

Failures:

  1) Alimento For, each y sort #Se realiza correctamente el each
     Failure/Error: expect(aux2).to eq([@food16,@food21, @food17, @food18, @food22, @food2, @food3, @food15, @food7, @food19, @food5, @food6, @food4, @food9, @food8, @food1, @food14, @food13, @food11, @food12, @food20, @food10])

     NameError:
       undefined local variable or method `aux2' for #<RSpec::ExampleGroups::Alimento::ForEachYSort:0x00000000e16c48>
     # ./spec/loop_spec.rb:57:in `block (3 levels) in <top (required)>'

Finished in 0.00202 seconds (files took 0.10498 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/loop_spec.rb:56 # Alimento For, each y sort #Se realiza correctamente el each

rake aborted!
Command failed with status (1): [rspec -I. spec/loop_spec.rb...]
/home/victoria/LPP17-18/practicaLPP/Rakefile:27:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)